# Generated by Django 4.1 on 2024-10-10 10:01

import bboard.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Objects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=10, verbose_name='Категория')),
                ('title', models.CharField(max_length=100, verbose_name='Название объекта')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('image_id', models.ImageField(blank=True, null=True, upload_to=bboard.models.image_path, verbose_name='Фотографии')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Объекты',
                'verbose_name_plural': 'Объект',
                'ordering': ['id'],
            },
        ),
    ]
